language: en
pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
  token_pattern: (?u)\b\w+\b
- name: EmbeddingIntentClassifier
- name: DucklingHTTPExtractor
  url: http://localhost:8000
  dimensions:
  - email
policies:
- name: FallbackPolicy
- name: AugmentedMemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
- name: EmbeddingPolicy
